name: check-app
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
 
jobs:
  check-app:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.2.3
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2
          
      - uses: rstudio/shinytest2/actions/test-app@v1
        with:
          app-dir: "."
          upload-snapshots: true